// components/Footer.tsx
import { FC, memo } from 'react';

const Footer: FC = () => {
  return (
    <footer className="flex justify-center items-center mt-auto font-mono text-lg text-blue-200 pb-4">
      Made with <img className="h-8 ml-2" alt="React logo" src="/react.svg" />
    </footer>
  );
};

export default memo(Footer);

// src/components/Footer.vue
<template>
  <footer class="footer">
   <p>
     Made with <img alt="Vue logo" src="../assets/logo.png"> & 💚
   </p>
  </footer>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Footer',
});
</script>

<style scoped lang="scss">

.footer {
 font-family: 'Courier New', Courier, monospace;
 display: flex;
 margin-top: auto;
 font-style: oblique;
 margin-bottom: 1rem;
 justify-content: center;
 align-items: center;
 font-size: 12px;

 ::before {
  content: "{";
  color: green;
 }

 ::after {
  content: "}";
  color: green;
 }

 img {
  height: 15px;
 }
}

</style>
